/** Supported guest languages */
window.PLATO_LANGS = [
  { code: "en", name: "English", native: "English", dir: "ltr" },
  { code: "es", name: "Spanish", native: "Español", dir: "ltr" },
  { code: "zh", name: "Chinese", native: "中文", dir: "ltr" },
  { code: "ko", name: "Korean", native: "한국어", dir: "ltr" },
  { code: "ja", name: "Japanese", native: "日本語", dir: "ltr" },
  { code: "vi", name: "Vietnamese", native: "Tiếng Việt", dir: "ltr" },
  { code: "pt", name: "Portuguese", native: "Português", dir: "ltr" },
  { code: "fr", name: "French", native: "Français", dir: "ltr" },
  { code: "ar", name: "Arabic", native: "العربية", dir: "rtl" },
  { code: "hi", name: "Hindi", native: "हिन्दी", dir: "ltr" },
  { code: "tl", name: "Filipino", native: "Filipino", dir: "ltr" },
  { code: "th", name: "Thai", native: "ไทย", dir: "ltr" },
  { code: "de", name: "German", native: "Deutsch", dir: "ltr" },
  { code: "it", name: "Italian", native: "Italiano", dir: "ltr" },
  { code: "ru", name: "Russian", native: "Русский", dir: "ltr" },
];

window.PLATO_LANG_CODES = PLATO_LANGS.map((l) => l.code);

/** UI strings — full for en/es; others fall back to en where missing */
window.PLATO_I18N = {
  en: {
    navMenu: "Demo menu",
    navAdmin: "Owner",
    navOwner: "Owner login",
    navDashboard: "Dashboard",
    navHome: "Plato",
    landingTitle: "The menu that speaks their language",
    landingSub:
      "Many languages, real plate photos, beautiful on any phone. Add a dish once — we translate it for every guest.",
    ctaGuest: "See demo guest menu",
    ctaOwner: "Owner sign in",
    ctaOwnerDashboard: "Open dashboard",
    ownerLoginTitle: "Welcome back",
    ownerLoginSub: "Sign in to manage your menu, scan a paper menu, and preview what guests see.",
    ownerLoginHint: "Use the email and password for your restaurant account.",
    ownerRegisterTitle: "Open your restaurant on Plato",
    ownerRegisterSub: "Create an owner account and name your place. Guests will see this name on your menu.",
    ownerRegisterHint: "You’ll set dishes, vibe, and QR after you sign up.",
    ownerHaveAccount: "Already have an account? Sign in",
    ownerNewAccount: "New restaurant? Create account",
    ownerDemoCreds: "Demo",
    apiConnected: "API connected",
    offlineMode: "Offline mode",
    signedInAs: "Signed in as",
    goDashboard: "Go to dashboard",
    needSignIn: "Sign in to continue",
    registerInstead: "Create account",
    createAccountBtn: "Create account",
    signInBtn: "Sign in",
    passwordConfirm: "Confirm password",
    passwordMismatch: "Passwords don’t match",
    feature1Title: "Many languages",
    feature1Body: "Guests pick English, Español, 中文, and more. One menu, every language.",
    feature2Title: "Real plates",
    feature2Body: "Upload kitchen photos. Guests can add shots you approve.",
    feature3Title: "Add once, translate all",
    feature3Body: "New item? Type it in your language. One tap fills every other language — then you can edit.",
    howTitle: "How it works",
    how1: "Guest scans your QR",
    how2: "Picks their language",
    how3: "Sees dishes + real photos",
    how4: "Orders with confidence",
    priceTitle: "Simple pricing",
    priceTruck: "Food truck / stall",
    priceRest: "Restaurant",
    priceNote: "Demo stores data in this browser only",
    footer: "Plato · Living menus for real tables",
    popular: "Popular",
    soldOut: "Sold out",
    spicy: "Spice",
    photos: "photos",
    guestPhotos: "Guest photos",
    official: "From the kitchen",
    allergens: "Allergens",
    orderHint: "Tell the counter this name — or show them this screen",
    helpTitle: "Not sure what to get?",
    helpBtn: "Help me choose",
    helpClose: "Close",
    helpQ1: "How hungry?",
    helpLight: "Light bite",
    helpFull: "Full meal",
    helpQ2: "Spice level?",
    helpMild: "Mild",
    helpHot: "Bring heat",
    helpQ3: "Prefer?",
    helpMeat: "Meat",
    helpVeg: "Veggie-friendly",
    helpResult: "We suggest",
    seeDish: "See dish",
    adminTitle: "Owner dashboard",
    adminSub: "Edit live. Guests see changes instantly.",
    adminMenu: "Menu items",
    adminPhotos: "Photo queue",
    adminQr: "Your QR",
    adminStats: "Tonight",
    adminAdd: "Add dish",
    adminAccount: "Account",
    adminLangs: "Languages",
    toggleSold: "Mark sold out",
    toggleAvail: "Mark available",
    approve: "Approve",
    reject: "Reject",
    pending: "Pending guest photos",
    scans: "Menu opens",
    langEs: "Non-English views",
    topDish: "Most opened dish",
    saveHint: "Saved in this browser. Translate new dishes to every language in one tap.",
    backMenu: "← Guest menu",
    close: "Close",
    copyQr: "Copy menu link",
    copied: "Copied!",
    all: "All",
    available: "Available",
    addDish: "Add new dish",
    editDish: "Edit dish",
    dishName: "Dish name",
    dishDesc: "Description",
    dishPrice: "Price",
    dishCategory: "Category",
    dishSpicy: "Spice (0–3)",
    dishPhoto: "Photo",
    primaryLang: "You are writing in",
    translateAll: "Translate to all languages",
    translating: "Translating…",
    translated: "Translated!",
    translateFail: "Some translations failed — edit manually",
    saveDish: "Save dish",
    deleteDish: "Delete",
    removeDish: "Remove",
    removeDishConfirm: "Remove this dish from the menu?",
    clearMenu: "Clear entire menu",
    clearMenuSub: "Removes all dishes. Restaurant settings and QR stay.",
    clearMenuConfirm: "Clear the entire menu? This cannot be undone.",
    clearMenuOk: "Yes, clear menu",
    menuEmpty: "No dishes yet. Scan a paper menu or add dishes in Setup.",
    deleteRestaurant: "Delete restaurant",
    deleteRestaurantConfirm: "Delete this restaurant and its full menu? This cannot be undone.",
    deleteRestaurantOk: "Yes, delete restaurant",
    deleteRestaurantBlocked: "Create another restaurant before deleting your last one.",
    dangerZone: "Danger zone",
    confirmAction: "Confirm",
    cancel: "Cancel",
    adminSections: "Sections",
    adminHome: "Home",
    adminImport: "Import",
    adminRestaurant: "Restaurant",
    adminProfile: "Profile",
    adminLive: "Go live",
    previewGuest: "Preview guest menu",
    wizardTitle: "Get live today",
    wizardSub: "Four steps to a guest-ready menu",
    adminOrders: "Orders",
    adminAnalytics: "Analytics",
    sectionsTitle: "Menu sections",
    sectionsSub: "Rename, reorder, or move dishes between sections. Guests see this structure.",
    sectionName: "Section name",
    addSection: "Add section",
    saveSections: "Save sections",
    moveDish: "Move to section",
    deleteSection: "Remove section",
    deleteSectionConfirm: "Remove this section? Dishes will move to another section.",
    sectionsSaved: "Sections saved",
    moveUp: "Up",
    moveDown: "Down",
    reviewLangs: "Review / edit translations",
    autoFilled: "Auto-translated — tap to edit",
    missingLang: "Missing",
    fillMissing: "Fill missing languages",
    enabledLangs: "Languages on your menu",
    enabledHint: "Guests only see languages you enable. New dishes auto-translate into these.",
    loginTitle: "Restaurant account",
    loginSub: "Update your restaurant name and account details.",
    restName: "Restaurant name",
    ownerEmail: "Email",
    password: "Password",
    signIn: "Sign in",
    signOut: "Sign out",
    uploadHint: "Take or choose a photo",
    noPhoto: "No photo yet",
    sourceNote: "How translation works: you write once in your primary language. We machine-translate into every enabled language. You can fix any line before guests see it.",
    accountSaved: "Account saved",
    dishSaved: "Dish saved",
    needName: "Add a dish name",
    needDesc: "Add a description",
  },
  es: {
    navMenu: "Menú demo",
    navAdmin: "Dueño",
    navOwner: "Entrar dueño",
    navDashboard: "Panel",
    navHome: "Plato",
    landingTitle: "El menú que habla su idioma",
    landingSub:
      "Muchos idiomas, fotos reales, bonito en el teléfono. Agrega un plato una vez — lo traducimos para cada cliente.",
    ctaGuest: "Ver menú de invitado",
    ctaOwner: "Entrar como dueño",
    ctaOwnerDashboard: "Abrir panel",
    ownerLoginTitle: "Bienvenido de nuevo",
    ownerLoginSub: "Entra para administrar tu menú, escanear el papel y ver lo que ven los clientes.",
    ownerLoginHint: "Usa el email y la contraseña de tu cuenta de restaurante.",
    ownerRegisterTitle: "Abre tu restaurante en Plato",
    ownerRegisterSub: "Crea una cuenta de dueño y nombra tu local. Los clientes verán este nombre en el menú.",
    ownerRegisterHint: "Después agregas platos, el estilo y el QR.",
    ownerHaveAccount: "¿Ya tienes cuenta? Entrar",
    ownerNewAccount: "¿Restaurante nuevo? Crear cuenta",
    ownerDemoCreds: "Demo",
    apiConnected: "API conectada",
    offlineMode: "Modo offline",
    signedInAs: "Sesión de",
    goDashboard: "Ir al panel",
    needSignIn: "Inicia sesión para continuar",
    registerInstead: "Crear cuenta",
    createAccountBtn: "Crear cuenta",
    signInBtn: "Entrar",
    passwordConfirm: "Confirmar contraseña",
    passwordMismatch: "Las contraseñas no coinciden",
    feature1Title: "Muchos idiomas",
    feature1Body: "El cliente elige English, Español, 中文 y más. Un menú, todos los idiomas.",
    feature2Title: "Platos reales",
    feature2Body: "Sube fotos de la cocina. Los clientes pueden mandar fotos que tú apruebas.",
    feature3Title: "Agrega una vez, traduce todo",
    feature3Body: "¿Platillo nuevo? Escríbelo en tu idioma. Un toque lo llena en los demás — y puedes editar.",
    howTitle: "Cómo funciona",
    how1: "El cliente escanea tu QR",
    how2: "Elige su idioma",
    how3: "Ve platos + fotos reales",
    how4: "Pide con confianza",
    priceTitle: "Precios simples",
    priceTruck: "Food truck / puesto",
    priceRest: "Restaurante",
    priceNote: "La demo guarda datos solo en este navegador",
    footer: "Plato · Menús vivos para mesas reales",
    popular: "Popular",
    soldOut: "Agotado",
    spicy: "Picante",
    photos: "fotos",
    guestPhotos: "Fotos de clientes",
    official: "De la cocina",
    allergens: "Alérgenos",
    orderHint: "Dile este nombre al mostrador — o muéstrales esta pantalla",
    helpTitle: "¿No sabes qué pedir?",
    helpBtn: "Ayúdame a elegir",
    helpClose: "Cerrar",
    helpQ1: "¿Cuánta hambre?",
    helpLight: "Algo ligero",
    helpFull: "Comida completa",
    helpQ2: "¿Qué tan picante?",
    helpMild: "Suave",
    helpHot: "Bien picante",
    helpQ3: "¿Prefieres?",
    helpMeat: "Carne",
    helpVeg: "Vegetariano",
    helpResult: "Te sugerimos",
    seeDish: "Ver plato",
    adminTitle: "Panel del dueño",
    adminSub: "Edita en vivo. El cliente lo ve al instante.",
    adminMenu: "Platillos",
    adminPhotos: "Cola de fotos",
    adminQr: "Tu QR",
    adminStats: "Esta noche",
    adminAdd: "Agregar plato",
    adminAccount: "Cuenta",
    adminLangs: "Idiomas",
    toggleSold: "Marcar agotado",
    toggleAvail: "Marcar disponible",
    approve: "Aprobar",
    reject: "Rechazar",
    pending: "Fotos de clientes pendientes",
    scans: "Aperturas del menú",
    langEs: "Vistas no-inglés",
    topDish: "Plato más abierto",
    saveHint: "Guardado en este navegador. Traduce platos nuevos a todos los idiomas en un toque.",
    backMenu: "← Menú del cliente",
    close: "Cerrar",
    copyQr: "Copiar enlace del menú",
    copied: "¡Copiado!",
    all: "Todo",
    available: "Disponible",
    addDish: "Agregar plato",
    editDish: "Editar plato",
    dishName: "Nombre del plato",
    dishDesc: "Descripción",
    dishPrice: "Precio",
    dishCategory: "Categoría",
    dishSpicy: "Picante (0–3)",
    dishPhoto: "Foto",
    primaryLang: "Estás escribiendo en",
    translateAll: "Traducir a todos los idiomas",
    translating: "Traduciendo…",
    translated: "¡Traducido!",
    translateFail: "Algunas traducciones fallaron — edita a mano",
    saveDish: "Guardar plato",
    deleteDish: "Eliminar",
    removeDish: "Quitar",
    removeDishConfirm: "¿Quitar este plato del menú?",
    clearMenu: "Vaciar menú completo",
    clearMenuSub: "Quita todos los platos. El restaurante y el QR se quedan.",
    clearMenuConfirm: "¿Vaciar todo el menú? No se puede deshacer.",
    clearMenuOk: "Sí, vaciar menú",
    menuEmpty: "Aún no hay platos. Escanea un menú o agrégalos en Setup.",
    deleteRestaurant: "Eliminar restaurante",
    deleteRestaurantConfirm: "¿Eliminar este restaurante y todo su menú? No se puede deshacer.",
    deleteRestaurantOk: "Sí, eliminar restaurante",
    deleteRestaurantBlocked: "Crea otro restaurante antes de borrar el último.",
    dangerZone: "Zona de peligro",
    confirmAction: "Confirmar",
    cancel: "Cancelar",
    adminSections: "Secciones",
    adminHome: "Inicio",
    adminImport: "Importar",
    adminRestaurant: "Restaurante",
    adminProfile: "Perfil",
    adminLive: "Publicar",
    previewGuest: "Vista del cliente",
    wizardTitle: "En vivo hoy",
    wizardSub: "Cuatro pasos para un menú listo",
    adminOrders: "Pedidos",
    adminAnalytics: "Analítica",
    sectionsTitle: "Secciones del menú",
    sectionsSub: "Renombra, reordena o mueve platos entre secciones. Así lo ven los clientes.",
    sectionName: "Nombre de sección",
    addSection: "Agregar sección",
    saveSections: "Guardar secciones",
    moveDish: "Mover a sección",
    deleteSection: "Quitar sección",
    deleteSectionConfirm: "¿Quitar esta sección? Los platos se moverán a otra.",
    sectionsSaved: "Secciones guardadas",
    moveUp: "Subir",
    moveDown: "Bajar",
    reviewLangs: "Revisar / editar traducciones",
    autoFilled: "Auto-traducido — toca para editar",
    missingLang: "Falta",
    fillMissing: "Completar idiomas faltantes",
    enabledLangs: "Idiomas en tu menú",
    enabledHint: "Los clientes solo ven los idiomas que actives. Los platos nuevos se traducen a estos.",
    loginTitle: "Cuenta del restaurante",
    loginSub: "Cuenta demo — solo en este dispositivo.",
    restName: "Nombre del restaurante",
    ownerEmail: "Correo",
    password: "Contraseña",
    signIn: "Guardar y continuar",
    signOut: "Cerrar sesión",
    uploadHint: "Toma o elige una foto",
    noPhoto: "Sin foto aún",
    sourceNote:
      "Cómo funciona la traducción: escribes una vez en tu idioma principal. Traducimos por máquina a cada idioma activo. Puedes corregir cualquier línea antes de que el cliente la vea.",
    accountSaved: "Cuenta guardada",
    dishSaved: "Plato guardado",
    needName: "Agrega un nombre",
    needDesc: "Agrega una descripción",
  },
};

/** Fallback: use en for UI if lang missing */
window.platoT = function platoT(lang, key) {
  const pack = PLATO_I18N[lang] || PLATO_I18N.en;
  return pack[key] || PLATO_I18N.en[key] || key;
};
