/** Default sample restaurant (EN + ES complete; others filled from EN on demand) */
window.PLATO_SEED = {
  restaurant: {
    id: "el-sol",
    name: "Taquería El Sol",
    tagline: {
      en: "Street tacos · Made fresh",
      es: "Tacos de la calle · Hechos al momento",
    },
    emoji: "🌮",
    address: {
      en: "Night market · Stall 12",
      es: "Mercado nocturno · Puesto 12",
    },
    hours: {
      en: "Open · Closes 11pm",
      es: "Abierto · Cierra 11pm",
    },
    accent: "#e85d04",
  },
  categories: [
    { id: "tacos", labels: { en: "Tacos", es: "Tacos", zh: "塔可", ko: "타코", ja: "タコス", fr: "Tacos", pt: "Tacos", vi: "Tacos", ar: "تاكو", de: "Tacos", it: "Tacos", hi: "टैकोस", tl: "Tacos", th: "ทาโก้", ru: "Тако" } },
    { id: "bowls", labels: { en: "Bowls", es: "Bowls", zh: "盖饭", ko: "볼", ja: "ボウル", fr: "Bols", pt: "Bowls", vi: "Tô", ar: "أطباق", de: "Bowls", it: "Bowl", hi: "बाउल", tl: "Bowls", th: "โบวล์", ru: "Боулы" } },
    { id: "sides", labels: { en: "Sides & drinks", es: "Acompañamientos y bebidas", zh: "配菜与饮品", ko: "사이드 & 음료", ja: "サイド＆ドリンク", fr: "Accompagnements", pt: "Acompanhamentos", vi: "Món phụ & đồ uống", ar: "جوانب ومشروبات", de: "Beilagen & Getränke", it: "Contorni e bevande", hi: "साइड और ड्रिंक", tl: "Sides at inumin", th: "เครื่องเคียงและเครื่องดื่ม", ru: "Гарниры и напитки" } },
  ],
  dishes: [
    {
      id: "al-pastor",
      category: "tacos",
      price: 4.5,
      popular: true,
      spicy: 2,
      soldOut: false,
      name: {
        en: "Al Pastor",
        es: "Al Pastor",
        zh: "牧羊人猪肉塔可",
        ko: "알 파스토르",
        ja: "アル・パストール",
        vi: "Al Pastor",
        pt: "Al Pastor",
        fr: "Al Pastor",
        ar: "أل باستور",
        hi: "अल पास्टर",
        tl: "Al Pastor",
        th: "อัล พาสตอร์",
        de: "Al Pastor",
        it: "Al Pastor",
        ru: "Аль-пастор",
      },
      desc: {
        en: "Marinated pork, pineapple, onion, cilantro on corn tortillas. Sweet heat from achiote and chile.",
        es: "Cerdo adobado, piña, cebolla y cilantro en tortilla de maíz. Dulce y picante con achiote y chile.",
        zh: "腌猪肉、菠萝、洋葱、香菜配玉米饼。胭脂树籽与辣椒的甜辣风味。",
        ko: "마리네이드 돼지고기, 파인애플, 양파, 고수를 옥수수 또띠아에. 아치오테와 칠리의 달콤한 매운맛.",
        ja: "マリネした豚肉、パイナップル、玉ねぎ、パクチーをコーントルティーヤで。アチオテとチリの甘辛い味わい。",
        fr: "Porc mariné, ananas, oignon, coriandre sur tortillas de maïs. Douce chaleur d'achiote et de piment.",
        pt: "Porco marinado, abacaxi, cebola e coentro em tortilhas de milho. Doce e picante com achiote e chile.",
        vi: "Thịt heo ướp, dứa, hành, ngò trên bánh ngô. Cay ngọt từ achiote và ớt.",
        ar: "لحم خنزير متبل وأناناس وبصل وكزبرة على تورتيلا الذرة. حرارة حلوة من الأشيوتي والفلفل.",
        de: "Mariniertes Schweinefleisch, Ananas, Zwiebel, Koriander auf Maistortillas. Süße Schärfe von Achiote und Chili.",
        it: "Maiale marinato, ananas, cipolla, coriandolo su tortillas di mais. Dolce piccante con achiote e peperoncino.",
        hi: "मैरीनेटेड पोर्क, अनानास, प्याज़, धनिया मक्के की टॉर्तिया पर। अचियोटे और मिर्च की मीठी तीखी गरम।",
        tl: "Marinado na baboy, pinya, sibuyas, cilantro sa corn tortilla. Matamis na anghang mula sa achiote at sili.",
        th: "หมูหมัก สับปะรด หอมใหญ่ ผักชี บนตอร์ติยาข้าวโพด เผ็ดหวานจากอาชิโอเตและพริก",
        ru: "Маринованная свинина, ананас, лук, кинза на кукурузных тортильях. Сладкая острота ачиоте и чили.",
      },
      tags: { en: ["Pork", "Signature"], es: ["Cerdo", "Especialidad"] },
      allergens: {
        en: "None common",
        es: "Sin alérgenos comunes",
        zh: "无常见过敏原",
        ko: "일반 알레르기 없음",
        ja: "一般的なアレルゲンなし",
        fr: "Aucun allergène courant",
        pt: "Sem alérgenos comuns",
        vi: "Không dị ứng phổ biến",
        ar: "بدون مسببات حساسية شائعة",
        de: "Keine üblichen Allergene",
        it: "Nessun allergene comune",
        hi: "सामान्य एलर्जन नहीं",
        tl: "Walang karaniwang allergen",
        th: "ไม่มีสารก่อภูมิแพ้ทั่วไป",
        ru: "Без обычных аллергенов",
      },
      photos: [
        "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
        "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=800&q=80",
        "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&q=80",
      ],
      photoCount: 14,
    },
    {
      id: "carnitas",
      category: "tacos",
      price: 4.25,
      popular: true,
      spicy: 1,
      soldOut: false,
      name: {
        en: "Carnitas",
        es: "Carnitas",
        zh: "墨西哥炖猪肉",
        ko: "카르니타스",
        ja: "カルニタス",
        fr: "Carnitas",
        pt: "Carnitas",
        vi: "Carnitas",
        ar: "كارنيتاس",
        de: "Carnitas",
        it: "Carnitas",
        hi: "कार्निटास",
        tl: "Carnitas",
        th: "คาร์นิตัส",
        ru: "Карнитас",
      },
      desc: {
        en: "Slow-cooked pork, crispy edges, salsa verde, onion. Rich and tender.",
        es: "Cerdo cocido lento, orillas crujientes, salsa verde y cebolla. Jugoso y suave.",
        zh: "慢炖猪肉，外酥里嫩，配绿酱和洋葱。",
        ko: "천천히 익힌 돼지고기, 바삭한 가장자리, 살사 베르데, 양파. 진하고 부드러움.",
        ja: "じっくり煮込んだ豚肉、カリッとした端、サルサベルデ、玉ねぎ。濃厚で柔らかい。",
        fr: "Porc mijoté, bords croustillants, salsa verde, oignon. Riche et tendre.",
        pt: "Porco cozido lentamente, bordas crocantes, salsa verde e cebola. Rico e macio.",
        vi: "Thịt heo hầm chậm, viền giòn, salsa xanh, hành. Đậm đà và mềm.",
        ar: "لحم خنزير مطهو ببطء، حواف مقرمشة، صلصة خضراء وبصل. غني وطري.",
        de: "Langsam gegartes Schweinefleisch, knusprige Ränder, Salsa Verde, Zwiebel. Saftig und zart.",
        it: "Maiale cotto a lungo, bordi croccanti, salsa verde, cipolla. Ricco e tenero.",
        hi: "धीमी पकी पोर्क, कुरकुरे किनारे, साल्सा वर्दे, प्याज़। भरपूर और नरम।",
        tl: "Mabagal na nilutong baboy, malutong na gilid, salsa verde, sibuyas. Mayaman at malambot.",
        th: "หมูตุ๋นช้า กรอบขอบ ซัลซ่าเขียว หอมใหญ่ นุ่มและเข้มข้น",
        ru: "Томлёная свинина, хрустящие края, сальса верде, лук. Сочная и нежная.",
      },
      tags: { en: ["Pork"], es: ["Cerdo"] },
      allergens: {
        en: "None common",
        es: "Sin alérgenos comunes",
      },
      photos: [
        "https://images.unsplash.com/photo-1613514785940-daed07799d9b?w=800&q=80",
        "https://images.unsplash.com/photo-1624300629298-e9de39c13be5?w=800&q=80",
      ],
      photoCount: 9,
    },
    {
      id: "asada",
      category: "tacos",
      price: 4.75,
      popular: false,
      spicy: 1,
      soldOut: false,
      name: {
        en: "Carne Asada",
        es: "Carne Asada",
        zh: "烤牛排塔可",
        ko: "카르네 아사다",
        ja: "カルネ・アサダ",
        fr: "Carne Asada",
        pt: "Carne Asada",
        vi: "Carne Asada",
        ar: "كارني أسادا",
        de: "Carne Asada",
        it: "Carne Asada",
        hi: "कार्ने असादा",
        tl: "Carne Asada",
        th: "คาร์เน่ อาซาดา",
        ru: "Карне асада",
      },
      desc: {
        en: "Grilled steak, chimichurri-style salsa, lime. Charred and juicy.",
        es: "Carne a la parrilla, salsa estilo chimichurri y limón. Tostada y jugosa.",
        zh: "烤牛排，青酱风味莎莎，青柠。外焦里嫩。",
        ko: "그릴 스테이크, 치미추리 스타일 살사, 라임. 그을리고 육즙 가득.",
        ja: "グリルステーキ、チミチュリ風サルサ、ライム。香ばしくジューシー。",
        fr: "Steak grillé, salsa façon chimichurri, citron vert. Grillé et juteux.",
        pt: "Bife grelhado, salsa estilo chimichurri e limão. Grelhado e suculento.",
        vi: "Bít tết nướng, salsa kiểu chimichurri, chanh. Thơm và mọng nước.",
        ar: "شريحة لحم مشوية، صلصة تشيميتشوري، ليمون. محمرة وعصيرية.",
        de: "Gegrilltes Steak, Chimichurri-Salsa, Limette. Röstaroma und saftig.",
        it: "Bistecca grigliata, salsa stile chimichurri, lime. Bruciacchiata e succosa.",
        hi: "ग्रिल्ड स्टेक, चिमीचुरी साल्सा, नींबू। चर्र और रसदार।",
        tl: "Inihaw na steak, chimichurri-style salsa, dayap. Charred at juicy.",
        th: "สเต็กย่าง ซัลซ่าแบบชิมิชูริ มะนาว หอมไหม้และฉ่ำ",
        ru: "Стейк на гриле, сальса в стиле чимичурри, лайм. С корочкой и сочный.",
      },
      tags: { en: ["Beef"], es: ["Res"] },
      allergens: { en: "None common", es: "Sin alérgenos comunes" },
      photos: [
        "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=800&q=80",
        "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&q=80",
      ],
      photoCount: 11,
    },
    {
      id: "veggie",
      category: "tacos",
      price: 4.0,
      popular: false,
      spicy: 2,
      soldOut: false,
      name: {
        en: "Nopales & Mushroom",
        es: "Nopales y Hongos",
        zh: "仙人掌与蘑菇",
        ko: "노팔레스 & 버섯",
        ja: "ノパレスとキノコ",
        fr: "Nopales et champignons",
        pt: "Nopal e cogumelos",
        vi: "Xương rồng & nấm",
        ar: "صبار وفطر",
        de: "Nopales & Pilze",
        it: "Nopales e funghi",
        hi: "नोपालेस और मशरूम",
        tl: "Nopal at kabute",
        th: "กระบองเพชรและเห็ด",
        ru: "Нопалес и грибы",
      },
      desc: {
        en: "Grilled cactus, mushrooms, salsa roja, queso fresco. Hearty vegetarian.",
        es: "Nopal asado, hongos, salsa roja y queso fresco. Vegetariano y contundente.",
        zh: "烤仙人掌、蘑菇、红莎莎、新鲜芝士。丰盛素食。",
        ko: "구운 선인장, 버섯, 살사 로하, 케소 프레스코. 푸짐한 채식.",
        ja: "焼いたサボテン、キノコ、サルサロハ、ケソフレスコ。ボリュームのあるベジ。",
        fr: "Cactus grillé, champignons, salsa roja, queso fresco. Végétarien copieux.",
        pt: "Cacto grelhado, cogumelos, salsa roja e queijo fresco. Vegetariano farto.",
        vi: "Xương rồng nướng, nấm, salsa đỏ, phô mai tươi. Chay no bụng.",
        ar: "صبار مشوي، فطر، صلصة حمراء، جبن طازج. نباتي دسم.",
        de: "Gegrillter Kaktus, Pilze, Salsa Roja, Queso Fresco. Herzhaft vegetarisch.",
        it: "Cactus grigliato, funghi, salsa roja, queso fresco. Vegetariano sostanzioso.",
        hi: "ग्रिल्ड कैक्टस, मशरूम, साल्सा रोहा, क़ेसो फ़्रेस्को। भरपूर शाकाहारी।",
        tl: "Inihaw na nopal, kabute, salsa roja, queso fresco. Hearty vegetarian.",
        th: "กระบองเพชรย่าง เห็ด ซัลซ่าแดง ชีสสด มังสวิรัติอิ่มท้อง",
        ru: "Кактус на гриле, грибы, сальса роха, свежий сыр. Сытное вегетарианское.",
      },
      tags: { en: ["Veggie"], es: ["Vegetariano"] },
      allergens: {
        en: "Dairy",
        es: "Lácteos",
        zh: "乳制品",
        ko: "유제품",
        ja: "乳製品",
        fr: "Produits laitiers",
        pt: "Laticínios",
        vi: "Sữa",
        ar: "ألبان",
        de: "Milchprodukte",
        it: "Latticini",
        hi: "डेयरी",
        tl: "Gatas",
        th: "นม",
        ru: "Молочные продукты",
      },
      photos: ["https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80"],
      photoCount: 3,
    },
    {
      id: "pastor-bowl",
      category: "bowls",
      price: 13.5,
      popular: true,
      spicy: 2,
      soldOut: false,
      name: {
        en: "Pastor Bowl",
        es: "Bowl al Pastor",
        zh: "牧羊人盖饭",
        ko: "파스토르 볼",
        ja: "パストールボウル",
        fr: "Bowl al Pastor",
        pt: "Bowl al Pastor",
        vi: "Tô Pastor",
        ar: "وعاء الباستور",
        de: "Pastor Bowl",
        it: "Bowl al Pastor",
        hi: "पास्टर बाउल",
        tl: "Pastor Bowl",
        th: "โบวล์พาสตอร์",
        ru: "Боул пастор",
      },
      desc: {
        en: "Al pastor pork, rice, beans, pineapple, pico, avocado crema. Full meal.",
        es: "Cerdo al pastor, arroz, frijoles, piña, pico y crema de aguacate. Comida completa.",
        zh: "牧羊人猪肉、米饭、豆、菠萝、洋葱番茄丁、牛油果酱。正餐。",
        ko: "알 파스토르 돼지고기, 밥, 콩, 파인애플, 피코, 아보카도 크레마. 한 끼 식사.",
        ja: "アル・パストールの豚肉、ご飯、豆、パイナップル、ピコ、アボカドクレマ。しっかり一食。",
        fr: "Porc al pastor, riz, haricots, ananas, pico, crème d'avocat. Repas complet.",
        pt: "Porco al pastor, arroz, feijão, abacaxi, pico e creme de abacate. Refeição completa.",
        vi: "Thịt heo pastor, cơm, đậu, dứa, pico, kem bơ. Bữa no.",
        ar: "لحم باستور، أرز، فاصوليا، أناناس، بيكو، كريمة أفوكادو. وجبة كاملة.",
        de: "Al-Pastor-Schweinefleisch, Reis, Bohnen, Ananas, Pico, Avocado-Crema. Sättigend.",
        it: "Maiale al pastor, riso, fagioli, ananas, pico, crema di avocado. Pasto completo.",
        hi: "अल पास्टर पोर्क, चावल, बीन्स, अनानास, पिको, एवोकाडो क्रीम। पूरा भोजन।",
        tl: "Al pastor na baboy, kanin, beans, pinya, pico, avocado crema. Buong pagkain.",
        th: "หมูพาสตอร์ ข้าว ถั่ว สับปะรด พิโก ครีมอะโวคาโด มื้ออิ่ม",
        ru: "Свинина аль-пастор, рис, фасоль, ананас, пико, крем из авокадо. Полный обед.",
      },
      tags: { en: ["Pork", "Filling"], es: ["Cerdo", "Contundente"] },
      allergens: { en: "Dairy", es: "Lácteos" },
      photos: [
        "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
        "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
      ],
      photoCount: 7,
    },
    {
      id: "asada-bowl",
      category: "bowls",
      price: 14.5,
      popular: false,
      spicy: 1,
      soldOut: true,
      name: {
        en: "Asada Bowl",
        es: "Bowl de Asada",
        zh: "烤牛肉盖饭",
        ko: "아사다 볼",
        ja: "アサダボウル",
        fr: "Bowl Asada",
        pt: "Bowl de Asada",
        vi: "Tô Asada",
        ar: "وعاء الأسادا",
        de: "Asada Bowl",
        it: "Bowl Asada",
        hi: "असादा बाउल",
        tl: "Asada Bowl",
        th: "โบวล์อาซาดา",
        ru: "Боул асада",
      },
      desc: {
        en: "Carne asada, cilantro rice, black beans, grilled onions, salsa.",
        es: "Carne asada, arroz con cilantro, frijoles negros, cebolla asada y salsa.",
        zh: "烤牛肉、香菜米饭、黑豆、烤洋葱、莎莎。",
        ko: "카르네 아사다, 고수 밥, 검은콩, 구운 양파, 살사.",
        ja: "カルネ・アサダ、シラントロライス、黒豆、焼き玉ねぎ、サルサ。",
        fr: "Carne asada, riz à la coriandre, haricots noirs, oignons grillés, salsa.",
        pt: "Carne asada, arroz com coentro, feijão preto, cebola grelhada e salsa.",
        vi: "Thịt asada, cơm ngò, đậu đen, hành nướng, salsa.",
        ar: "لحم أسادا، أرز بالكزبرة، فاصوليا سوداء، بصل مشوي، صلصة.",
        de: "Carne asada, Korianderreis, schwarze Bohnen, gegrillte Zwiebeln, Salsa.",
        it: "Carne asada, riso al coriandolo, fagioli neri, cipolle grigliate, salsa.",
        hi: "कार्ने असादा, धनिया चावल, काली फलियाँ, ग्रिल्ड प्याज़, साल्सा।",
        tl: "Carne asada, cilantro rice, black beans, inihaw na sibuyas, salsa.",
        th: "เนื้ออาซาดา ข้าวผักชี ถั่วดำ หอมใหญ่ย่าง ซัลซ่า",
        ru: "Карне асада, рис с кинзой, чёрная фасоль, лук на гриле, сальса.",
      },
      tags: { en: ["Beef"], es: ["Res"] },
      allergens: { en: "None common", es: "Sin alérgenos comunes" },
      photos: ["https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80"],
      photoCount: 5,
    },
    {
      id: "elote",
      category: "sides",
      price: 5.0,
      popular: true,
      spicy: 1,
      soldOut: false,
      name: {
        en: "Elote",
        es: "Elote",
        zh: "墨西哥街头玉米",
        ko: "엘로테",
        ja: "エロテ",
        fr: "Elote",
        pt: "Elote",
        vi: "Elote",
        ar: "إلوتي",
        de: "Elote",
        it: "Elote",
        hi: "एलोते",
        tl: "Elote",
        th: "เอโลเต",
        ru: "Элоте",
      },
      desc: {
        en: "Street corn, mayo, cotija, chile powder, lime. Messy in the best way.",
        es: "Elote de la calle, mayonesa, cotija, chile y limón. Rico y desordenado.",
        zh: "街头玉米、蛋黄酱、科提贾奶酪、辣椒粉、青柠。好吃又过瘾。",
        ko: "길거리 옥수수, 마요, 코티하, 칠리 가루, 라임. messy해도 최고.",
        ja: "ストリートコーン、マヨ、コティハ、チリパウダー、ライム。messyだけど最高。",
        fr: "Maïs de rue, mayo, cotija, piment, citron vert. Délicieusement désordonné.",
        pt: "Milho de rua, maionese, cotija, pimenta e limão. Bagunçado e delicioso.",
        vi: "Bắp đường phố, mayo, phô mai cotija, ớt bột, chanh. Bẩn tay mà ngon.",
        ar: "ذرة الشارع، مايونيز، جبن كوتيجا، فلفل، ليمون. فوضوي ولذيذ.",
        de: "Straßenmais, Mayo, Cotija, Chilipulver, Limette. Herrlich messy.",
        it: "Mais di strada, mayo, cotija, peperoncino, lime. Disordinato e buono.",
        hi: "स्ट्रीट कॉर्न, मेयो, कोटिजा, मिर्च पाउडर, नींबू। मज़ेदार messy।",
        tl: "Street corn, mayo, cotija, chili powder, dayap. Messy pero masarap.",
        th: "ข้าวโพดข้างทาง มายองเนส ชีสโคติฮา พริกป่น มะนาว เลอะแต่คุ้ม",
        ru: "Уличная кукуруза, майо, котиха, чили, лайм. Вкусно и messy.",
      },
      tags: { en: ["Side", "Veggie"], es: ["Acompañamiento", "Vegetariano"] },
      allergens: { en: "Dairy, Eggs", es: "Lácteos, Huevo" },
      photos: ["https://images.unsplash.com/photo-1651352650142-385087834d9d?w=800&q=80"],
      photoCount: 18,
    },
    {
      id: "horchata",
      category: "sides",
      price: 3.5,
      popular: false,
      spicy: 0,
      soldOut: false,
      name: {
        en: "Horchata",
        es: "Horchata",
        zh: "米浆",
        ko: "오르차타",
        ja: "オルチャータ",
        fr: "Horchata",
        pt: "Horchata",
        vi: "Horchata",
        ar: "هورتشاتا",
        de: "Horchata",
        it: "Horchata",
        hi: "हॉरचाटा",
        tl: "Horchata",
        th: "ฮอร์ชาตา",
        ru: "Орчата",
      },
      desc: {
        en: "House rice milk, cinnamon, vanilla. Cold and sweet.",
        es: "Agua de arroz de la casa, canela y vainilla. Fría y dulce.",
        zh: "自制米浆、肉桂、香草。冰凉香甜。",
        ko: "하우스 쌀 음료, 시나몬, 바닐라. 차갑고 달콤.",
        ja: "自家製ライスミルク、シナモン、バニラ。冷たく甘い。",
        fr: "Lait de riz maison, cannelle, vanille. Froid et sucré.",
        pt: "Leite de arroz da casa, canela e baunilha. Gelado e doce.",
        vi: "Sữa gạo nhà làm, quế, vani. Lạnh và ngọt.",
        ar: "حليب أرز منزلي، قرفة، فانيليا. بارد وحلو.",
        de: "Hausgemachte Reismilch, Zimt, Vanille. Kalt und süß.",
        it: "Latte di riso della casa, cannella, vaniglia. Freddo e dolce.",
        hi: "घर का राइस मिल्क, दालचीनी, वनीला। ठंडा और मीठा।",
        tl: "House rice milk, kanela, banilya. Malamig at matamis.",
        th: "นมข้าวสูตรบ้าน อบเชย วานิลลา เย็นและหวาน",
        ru: "Домашнее рисовое молоко, корица, ваниль. Холодное и сладкое.",
      },
      tags: { en: ["Drink"], es: ["Bebida"] },
      allergens: { en: "None common", es: "Sin alérgenos comunes" },
      photos: ["https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&q=80"],
      photoCount: 2,
    },
    {
      id: "agua-fresca",
      category: "sides",
      price: 3.5,
      popular: false,
      spicy: 0,
      soldOut: false,
      name: {
        en: "Agua Fresca (Jamaica)",
        es: "Agua Fresca (Jamaica)",
        zh: "洛神花水",
        ko: "아과 프레스카 (히비스커스)",
        ja: "アグアフレスカ（ハイビスカス）",
        fr: "Agua Fresca (Jamaica)",
        pt: "Agua Fresca (Jamaica)",
        vi: "Agua Fresca (Hoa bụp giấm)",
        ar: "أغوا فريسكا (كركديه)",
        de: "Agua Fresca (Hibiskus)",
        it: "Agua Fresca (Ibisco)",
        hi: "आगुआ फ्रेस्का (हिबिस्कस)",
        tl: "Agua Fresca (Jamaica)",
        th: "อากัว เฟรสกา (กระเจี๊ยบ)",
        ru: "Агуа фреска (гибискус)",
      },
      desc: {
        en: "Hibiscus agua fresca, lightly sweet, ice-cold.",
        es: "Agua de jamaica, poco dulce y bien fría.",
        zh: "洛神花饮，微甜，冰镇。",
        ko: "히비스커스 아과 프레스카, 살짝 달고 아주 차가움.",
        ja: "ハイビスカスのアグアフレスカ、ほのかな甘さ、冷たい。",
        fr: "Agua fresca d'hibiscus, légèrement sucrée, bien froide.",
        pt: "Agua fresca de hibisco, levemente doce e bem gelada.",
        vi: "Nước hoa bụp giấm, hơi ngọt, lạnh.",
        ar: "شراب كركديه خفيف الحلاوة وبارد جداً.",
        de: "Hibiskus-Agua Fresca, leicht süß, eiskalt.",
        it: "Agua fresca all'ibisco, leggermente dolce, ghiacciata.",
        hi: "हिबिस्कस आगुआ फ्रेस्का, हल्की मीठी, बर्फ़ जैसी ठंडी।",
        tl: "Hibiscus agua fresca, bahagyang matamis, napakalamig.",
        th: "น้ำกระเจี๊ยบ หวานเล็กน้อย เย็นจัด",
        ru: "Агуа фреска из гибискуса, слегка сладкая, ледяная.",
      },
      tags: { en: ["Drink"], es: ["Bebida"] },
      allergens: { en: "None common", es: "Sin alérgenos comunes" },
      photos: ["https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=800&q=80"],
      photoCount: 1,
    },
  ],
  pendingPhotos: [
    {
      id: "p1",
      dishId: "al-pastor",
      url: "https://images.unsplash.com/photo-1624300629298-e9de39c13be5?w=400&q=80",
    },
    {
      id: "p2",
      dishId: "elote",
      url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&q=80",
    },
  ],
};
